name: source_span
version: 1.5.6-dev

description: A library for identifying source spans and locations.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/source_span

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  charcode: ^1.0.0
  path: '>=1.2.0 <2.0.0'
  term_glyph: ^1.0.0

dev_dependencies:
  test: ^1.0.0
