name: source_span
version: 1.8.0-nullsafety.5-dev

description: A library for identifying source spans and locations.
homepage: https://github.com/dart-lang/source_span

environment:
  sdk: ">=2.12.0-0.0 <3.0.0"

dependencies:
  collection: '>=1.15.0-nullsafety <1.15.0'
  path: '>=1.8.0-nullsafety <1.8.0'
  term_glyph: '>=1.2.0-nullsafety <1.2.0'

dev_dependencies:
  test: ^1.16.0-nullsafety
