name: source_span
version: 1.9.2-dev
description: A library for identifying source spans and locations.
repository: https://github.com/dart-lang/source_span

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  path: ^1.8.0
  term_glyph: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
