name: source_span
version: 1.8.0-nullsafety.3

description: A library for identifying source spans and locations.
homepage: https://github.com/dart-lang/source_span

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.11.0-0.0 <2.12.0'

dependencies:
  charcode: '>=1.2.0-nullsafety <1.2.0'
  collection: '>=1.15.0-nullsafety <1.15.0'
  path: '>=1.8.0-nullsafety <1.8.0'
  term_glyph: '>=1.2.0-nullsafety <1.2.0'

dev_dependencies:
  test: ^1.16.0-nullsafety
